### ISSUE TITLE
snapexport.sh error or tar

### ISSUE THREAD

**Issue by user8446** [scubamuc/scubamuc.github.io#2]
Hi,

Thank you for the [snapexport.sh](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/bash-scripts/snapexport.sh) script.

It would error out on the tar command:
```
tar: 20240203-131607: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

I removed the hyphen from the tar options which allowed it to work per: https://unix.stackexchange.com/questions/149494/tar-exits-on-cannot-stat-no-such-file-of-directory-why

Also, the original backups will forever accumulate in the backups folder which I didn't want (but some users may) so I added the removal in the script. Maybe add it there too for the users and they can comment it if they want to:

```
# Remove original backups
sudo rm -r /var/snap/nextcloud/common/backups/*
```

Thanks again!

**Comment by scubamuc** [comment]
Hi @user8446, my pleasure glad you could use the script and thanks for the heads up.

> the original backups will forever accumulate in the backups folder which I didn't want 

Why don't you use the rotation option? That way you'd retain backups for 30 days before they'd be deleted automatically.

I must admit, I don't use that Script any more since my Nextcloud snap is now in an LXC container and I prefer to snapshot the entire container. See here https://github.com/scubamuc/scubamuc.github.io/tree/scubamuc and LXC container snapshot [scripted](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/bash-scripts/LXC-ContainerBackup.sh).

I'm quite chuffed that some folks actually read my stuff and use my novice scripts :+1:

**Comment by scubamuc** [comment]
Hey @user8446,

reading your issue and trying to figure out where the problem is with the tar command

>  would error out on the tar command

I'd like to suggest to rather use the [snapsnapshot.sh](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--backup_snap-snapshot.md) script. That method is more stable and much simpler to restore and will give you the added advantage of easy migration to a different device, should your hardware ever fail on you. Also the snap snapshot script automatically packs the backup into a `zip` which can be copied to wherever you like. That'll be nicer to your system resources and lets you rotate your backups nicely too.

Feel free to give me a shout if you have questions.

**Comment by user8446** [comment]
> Why don't you use the rotation option? That way you'd retain backups for 30 days before they'd be deleted automatically.

Yes, the backups will rotate in the destination folder. I was referring to the originals in `/var/snap/nextcloud/common/backups`.

> I'd like to suggest to rather use the [snapsnapshot.sh](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap--backup_snap-snapshot.md) script.

Thank you for the suggestion and will try that as well. It seems the main different between the two options is with the import/export option you can [selectively choose apps, database, config, and data](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Export-and-Import).

**Comment by scubamuc** [comment]
> I was referring to the originals in /var/snap/nextcloud/common/backups.

@user8446 you're absolutely right, that could be solved with
```
# Remove original backups
sudo rm -r /var/snap/nextcloud/common/backups/*
```
> It seems the main different between the two options is with the import/export option you can [selectively choose apps, database, config, and data](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Export-and-Import).

I believe there's a bit more to it. For one, the snap way of backing up is much more complete. Being one of the selling points of Canonicals snaps. You're taking the entire snap container, packing it in a neat bundle which can be transferred wherever and will work almost anywhere upon restoring it. That makes it great for migration. Additionally snapshots can be taken of a running snap without needing to shut down your snap first so you have zero downtime. Of course its highly recommended to stop the snap before snapshot, but that's optional.

Either way, you're doing a great job backing up your Nextcloud in the first place. Good for you 👍
